### ISSUE TITLE
offhand food

### ISSUE THREAD

**Issue by 909oce** [FakeDomi/Infinities#1]
if you have food in offhand and are missing any hunger (basically if you can eat) the bow in main hand will get stuck isntead youll be eating/holding the bow forever until you release right click and choose only to hold 1. its hard to explain, id recommend just trying it out for yourself.

**Comment by 909oce** [comment]
this issue only happens if you have 0 arrows, if you have atleast 1 it works fine, which is how i came to the conclusion it must be a bug with this mod specifically

**Comment by FakeDomi** [comment]
do you by chance have the mod installed server side only? that could explain it

**Comment by 909oce** [comment]
ah yep, ill try with it on both sides

**Comment by FakeDomi** [comment]
this is not possible to fix when the mod is installed on the server only since the client picks which hand to use
